### ISSUE TITLE
Troubles to build

### ISSUE THREAD

**Issue by ar-valdez** [aharwood2/LUMA#14]
Dear @aharwood2 as suggested I open this issue, regarding my building problem.

Hello, I have read the previous closed issues concerning the installation and execution of LUMA.

I have installed the serial version of `hdf5`, and its
located in the next address: `/usr/include/hdf5`

As you can see I exported the path, no errors came out,
I assume it was ok.

`(base) valdez@lmpnote05:/media/valdez/data/LUMA/LUMA$ export HDF5_HOME=/usr/include/hdf5`

I assume the previous export command was well executed, no errors or warnings appeared. 

Then I call the `make` command and I get the next terminal output:

`(base) valdez@lmpnote05:/media/valdez/data/LUMA/LUMA$ make`
`mkdir -p obj`
`mpicxx -O3 -std=c++0x -w -fopenmp -I/usr/include/hdf5/include -c -o obj/GridObj_init_grids.o src/GridObj_init_grids.cpp`
`mpicxx -O3 -std=c++0x -w -fopenmp -I/usr/include/hdf5/include -c -o obj/ObjectManager.o src/ObjectManager.cpp`
`mpicxx -O3 -std=c++0x -w -fopenmp -I/usr/include/hdf5/include -c -o obj/MpiManager_fem.o src/MpiManager_fem.cpp`
`mpicxx -O3 -std=c++0x -w -fopenmp -I/usr/include/hdf5/include -c -o obj/IBMarker.o src/IBMarker.cpp`
`mpicxx -O3 -std=c++0x -w -fopenmp -I/usr/include/hdf5/include -c -o obj/FEMNode.o src/FEMNode.cpp`
`mpicxx -O3 -std=c++0x -w -fopenmp -I/usr/include/hdf5/include -c -o obj/ObjectManager_ops_io.o src/ObjectManager_ops_io.cpp`
`mpicxx -O3 -std=c++0x -w -fopenmp -I/usr/include/hdf5/include -c -o obj/IBInfo.o src/IBInfo.cpp`
`mpicxx -O3 -std=c++0x -w -fopenmp -I/usr/include/hdf5/include -c -o obj/FEMBody.o src/FEMBody.cpp`
`mpicxx -O3 -std=c++0x -w -fopenmp -I/usr/include/hdf5/include -c -o obj/BFLBody.o src/BFLBody.cpp`
`mpicxx -O3 -std=c++0x -w -fopenmp -I/usr/include/hdf5/include -c -o obj/IBBody.o src/IBBody.cpp`
`mpicxx -O3 -std=c++0x -w -fopenmp -I/usr/include/hdf5/include -c -o obj/GridManager.o src/GridManager.cpp`
`mpicxx -O3 -std=c++0x -w -fopenmp -I/usr/include/hdf5/include -c -o obj/ObjectManager_ops_ibm_debug.o src/ObjectManager_ops_ibm_debug.cpp`
`mpicxx -O3 -std=c++0x -w -fopenmp -I/usr/include/hdf5/include -c -o obj/BFLMarker.o src/BFLMarker.cpp`
`mpicxx -O3 -std=c++0x -w -fopenmp -I/usr/include/hdf5/include -c -o obj/Mpi_buffer_size_send.o src/Mpi_buffer_size_send.cpp`
`mpicxx -O3 -std=c++0x -w -fopenmp -I/usr/include/hdf5/include -c -o obj/main_lbm.o src/main_lbm.cpp`
`mpicxx -O3 -std=c++0x -w -fopenmp -I/usr/include/hdf5/include -c -o obj/GridObj_ops_lbm.o src/GridObj_ops_lbm.cpp`
`mpicxx -O3 -std=c++0x -w -fopenmp -I/usr/include/hdf5/include -c -o obj/Mpi_buffer_size_recv.o src/Mpi_buffer_size_recv.cpp`
`mpicxx -O3 -std=c++0x -w -fopenmp -I/usr/include/hdf5/include -c -o obj/stdafx.o src/stdafx.cpp`
`mpicxx -O3 -std=c++0x -w -fopenmp -I/usr/include/hdf5/include -c -o obj/ObjectManager_ops_ibm_mpi.o src/ObjectManager_ops_ibm_mpi.cpp`
`mpicxx -O3 -std=c++0x -w -fopenmp -I/usr/include/hdf5/include -c -o obj/GridObj_ops_lbm_optimised.o src/GridObj_ops_lbm_optimised.cpp`
`mpicxx -O3 -std=c++0x -w -fopenmp -I/usr/include/hdf5/include -c -o obj/Mpi_buffer_unpk.o src/Mpi_buffer_unpk.cpp`
`mpicxx -O3 -std=c++0x -w -fopenmp -I/usr/include/hdf5/include -c -o obj/GridObj.o src/GridObj.cpp`
`mpicxx -O3 -std=c++0x -w -fopenmp -I/usr/include/hdf5/include -c -o obj/Mpi_buffer_pack.o src/Mpi_buffer_pack.cpp`
`mpicxx -O3 -std=c++0x -w -fopenmp -I/usr/include/hdf5/include -c -o obj/MpiManager.o src/MpiManager.cpp`
`mpicxx -O3 -std=c++0x -w -fopenmp -I/usr/include/hdf5/include -c -o obj/FEMElement.o src/FEMElement.cpp`
`mpicxx -O3 -std=c++0x -w -fopenmp -I/usr/include/hdf5/include -c -o obj/GridUtils.o src/GridUtils.cpp`
`mpicxx -O3 -std=c++0x -w -fopenmp -I/usr/include/hdf5/include -c -o obj/MpiManager_ibm.o src/MpiManager_ibm.cpp`
`mpicxx -O3 -std=c++0x -w -fopenmp -I/usr/include/hdf5/include -c -o obj/GridObj_ops_io.o src/GridObj_ops_io.cpp`
`In file included from src/GridObj_ops_io.cpp:28:0:`
`src/../inc/hdf5luma.h:31:10: fatal error: hdf5.h: No such file or directory`
` #include "hdf5.h" // Load C API`
 `         ^~~~~~~~`
`compilation terminated.`
`makefile:37: recipe for target 'obj/GridObj_ops_io.o' failed`
`make: *** [obj/GridObj_ops_io.o] Error 1`

Looking after the comments and responses from the community I salute you.

**Comment by aharwood2** [comment]
Hi, thanks for opening the issue. You are really supposed to install the parallel version of HDF5 as per the installation instructions. Typically your linking will fail if you try to link against the serial version. However, at the moment your compilation is failing so let's start with that. Can you confirm that the file `hdf5.h` is indeed present at the path: `/usr/include/hdf5/include` which is where the makefile is looking for it?

**Comment by ar-valdez** [comment]
Thanks for the reply @aharwood2 . I am trying to install the parallel version of `hdf5`....

I have one question: Which version have you used for  `hdf5`? I noticed in the  `hdf5` website there is no longer maintenance... I am getting errors in the parallel installation. This is a excerpt of my installation guide:

`2.1. Know parallel compilers`
`----------------------------`
`HDF5 knows several parallel compilers: mpicc, hcc, mpcc, mpcc_r.  To build`
`parallel HDF5 with one of the above, just set CC as it and configure.`

`    $ CC=/usr/local/mpi/bin/mpicc ./configure --enable-parallel --prefix=<install-directory>`
`    $ make		# build the library`
`    $ make check	# verify the correctness`
`			# Read the Details section about parallel tests.`
`    $ make install`


Just one comment, for example inside the `/usr/include/mpi` folder I have the next files and folders:
`mpi-ext.h                mpif-config.h     mpif-externals.h  mpif.h          mpif-io-constants.h  mpif-sentinels.h  mpi.h                    mpp      openshmem  pshmem.h   shmem-compat.h  shmem.h
mpif-c-constants-decl.h  mpif-constants.h  mpif-ext.h        mpif-handles.h  mpif-io-handles.h    mpif-sizeof.h     mpi_portable_platform.h  openmpi  pmix       pshmemx.h  shmem.fh        shmemx.h`

I tried to configure the installation with the following call `./configure --prefix=/usr/local/hdf5 --enable-parallel`.... I even enable `fortran` but it didn't passed the `make check` call.

**Comment by aharwood2** [comment]
Are you following our [installation guide](https://github.com/aharwood2/LUMA/wiki/Building-Dependencies)? It states quite clearly what version we are using and how to install it on Ubuntu. If this is out of date, please let us know and I can update the docs.

**Comment by ar-valdez** [comment]
Dear @aharwood2  I have downloaded the version `HDF5 1.8.17` version, I assume its the same as in the installation guide link you shared before.

I have done the following steps
1) `sudo apt-get install mpich` regarding MPI let me share this message from terminal `libopenmpi-dev is already the newest version (2.1.1-8)`, this came after calling `sudo apt-get install libopenmpi-dev`.
2) Following [link to install paralell hdf5](https://support.hdfgroup.org/ftp/HDF5/current/src/unpacked/release_docs/INSTALL_parallel) I wrote in the terminal the following command `CC=/usr/lib/mpich/include`.
3) After I executed the configuration step `./configure --enable-parallel --enable-fortran --prefix=/usr/local/hdf5`
4) later `make` (no problems)
5) After `make check` and here comes the problem I reported before. Let me share and excerpt of the error:
`Makefile:1306: recipe for target 't_pflush1.chkexe_' failed`
`make[4]: *** [t_pflush1.chkexe_] Error 1`
`make[4]: Leaving directory '/home/valdez/CMake-hdf5-1.8.17/hdf5-1.8.17/testpar'`
`Makefile:1381: recipe for target 'build-check-p' failed`
`make[3]: *** [build-check-p] Error 1`
`make[3]: Leaving directory '/home/valdez/CMake-hdf5-1.8.17/hdf5-1.8.17/testpar'`
`Makefile:1286: recipe for target 'test' failed`
`make[2]: *** [test] Error 2`
`make[2]: Leaving directory '/home/valdez/CMake-hdf5-1.8.17/hdf5-1.8.17/testpar'`
`Makefile:1089: recipe for target 'check-am' failed`
`make[1]: *** [check-am] Error 2`
`make[1]: Leaving directory '/home/valdez/CMake-hdf5-1.8.17/hdf5-1.8.17/testpar'`
`Makefile:576: recipe for target 'check-recursive' failed`
`make: *** [check-recursive] Error 1`

Can you tell me how to fix the `make check` step? OR should I ignore it and `make install`?

Thanks.-

**Comment by aharwood2** [comment]
I'm still not sure why you are doing steps 2-4. What Linux distro are you using?

On our Ubuntu systems we just type: `sudo apt-get install mpich` followed by `sudo apt-get install libhdf5-mpich-dev` as it says in the installation guide to install the packages. Why are you trying to build something with make? We don't tell you to do we?

Why do you call `sudo apt-get install libopenmpi-dev`? This installs OpenMPI. You already have MPICH installed. If you install both side-by-side I guarantee you are causing yourself a world of pain. We don't tell you to install OpenMPI in the instructions so why have you?

My suggestion is to purge your packages and follow the [installation instructions](https://github.com/aharwood2/LUMA/wiki/Building-Dependencies) to the letter.

**Comment by ar-valdez** [comment]
Dear @aharwood2 , I did steps 2-4, because I thought that LUMA needed hdf5 library installed..... I will just then do this steps:
`sudo apt-get install mpich`,
`sudo apt-get install libhdf5-mpich-dev`,

and after go back to LUMA's installation, is this ok?

**Comment by aharwood2** [comment]
Line 2 of what you typed installs HDF5 -- that is why the package name has hdf5 in it..

If you stick with the instructions you shouldn't run into any more problems.

**Comment by ar-valdez** [comment]
Dear @aharwood2, before closing, I have one last comment. Inside the path `/usr/include/hdf5/mpich` contains the `hdf5.h` file. I export the path  for LUMA's building`export HDF5_HOME=/usr/include/hdf5/mpich` and get the following error after `make` command:
`src/../inc/hdf5luma.h:31:10: fatal error: hdf5.h: No such file or directory`
` #include "hdf5.h" // Load C API`
`          ^~~~~~~~`
`compilation terminated.`
`makefile:37: recipe for target 'obj/GridObj_ops_io.o' failed`
`make: *** [obj/GridObj_ops_io.o] Error 1`

Thanks for the help.

**Comment by ianhinder** [comment]
Please can you tell us 
1. the operating system you are running on
2. the instructions you are following

**Comment by ar-valdez** [comment]
dear @ianhinder I am working on ubuntu 18.04.4 LTS. I have executed the following steps:

`export HDF5_HOME=/usr/include/hdf5/mpich`

`make` in the directory where the `makefile` is located....

**Comment by ianhinder** [comment]
Thanks.  Please can you answer no 2 - which instructions are you following?  Is it https://github.com/aharwood2/LUMA/wiki/Installing-LUMA, and then https://github.com/aharwood2/LUMA/wiki/Building-Dependencies?  I just want to make sure we are all talking about the same instructions.

**Comment by ar-valdez** [comment]
dear @ianhinder I understood your question. Let me explain.

Firstly from [here](https://github.com/aharwood2/LUMA/wiki/Building-Dependencies) I executed the terminal commands `sudo apt-get install mpich` and `sudo apt-get install libhdf5-mpich-dev` in that order. Everything was fine.

And secondly from [here](https://github.com/aharwood2/LUMA/wiki/Installing-LUMA) I imported the path:
`export HDF5_HOME=/usr/include/hdf5/mpich` the path is correct and exists and contains the header file `hdf5.h`. Later I gave `make` inside the `LUMA/LUMA` folder and the error came out.

**Comment by ianhinder** [comment]
I think I see the problem - the instructions say to use
```
export HDF5_HOME=/usr/lib/x86_64-linux-gnu/hdf5/mpich
```
but you have set 
```
export HDF5_HOME=/usr/include/hdf5/mpich
```
Can you try with the first one?  Make sure to run "make clean" before "make" to remove the results of the previous incorrect compilation.

**Comment by ar-valdez** [comment]
dear @ianhinder problem solved. Thank you very much... I compiled and obtain the executable LUMA.....
During the execution of `mpirun -np 6 ./LUMA ` I get the following message (many times, like once per iteration)
`HDF5-DIAG: Error detected in HDF5 (1.10.0-patch1) thread 0:`
`  #000: ../../../src/H5Dio.c line 225 in H5Dwrite(): not a dataset`
`    major: Invalid arguments to routine`
`    minor: Inappropriate type`

Is this ok?

**Comment by ianhinder** [comment]
Apologies for the delay in replying.  
1. Please can you send (as a file attachment to a comment) the output of "dpkg -l"?  This will list all the packages installed on your system.  I'm thinking you might have a mixture of different MPI and HDF5 versions.
2. Please can you also send the rank 0 logfile? This will be in the output directory output_\<date>/log_rank0.log.

**Comment by ar-valdez** [comment]
Dear @ianhinder please find attached the requested files.
[dpkg_output.txt](https://github.com/aharwood2/LUMA/files/4733179/dpkg_output.txt)
[log_rank0.log](https://github.com/aharwood2/LUMA/files/4733181/log_rank0.log)

**Comment by ianhinder** [comment]
You have both openmpi and mpich libraries installed.  I'm not sure if this is causing the problem, but it can sometimes be an issue.  Can you try removing all the openmpi related ones with
```
apt remove libhdf5-openmpi-100 libopenmpi-dev libopenmpi2 openmpi-bin openmpi-common
```
then "make clean" and "make" again in the LUMA directory, and try the simulation again.

The error message is actually saying that LUMA failed to write to the HDF5 files, which is a bit strange.  Is it possible that you don't have enough disk space?
